digipoc:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: airbyte #helloworld # ClickHouse database for dbt models

      # Optional
      host: localhost
      port: 8123 # Defaults to 8123, 8443, 9000, 9440 depending on the secure and driver settings
      user: airflow # User for all database operations
      password: changemepls # Password for the user
      secure: false  # Use TLS (native protocol) or HTTPS (http protocol)

    prod:
      type: clickhouse
      schema: airbyte # ClickHouse database for dbt models

      # Optional
      host: chi-digipoc-cluster1-0-0.clickhouse-installation.svc.cluster.local
      port: 8123 # Defaults to 8123, 8443, 9000, 9440 depending on the secure and driver settings
      user: airflow # User for all database operations
      password: changemepls # Password for the user
      secure: false  # Use TLS (native protocol) or HTTPS (http protocol)